package cn.xiaojs.xma.util;
/*  =======================================================================================
 *  Copyright (C) 2016 Xiaojs.cn. All rights reserved.
 *
 *  This computer program source code file is protected by copyright law and international
 *  treaties. Unauthorized distribution of source code files, programs, or portion of the
 *  package, may result in severe civil and criminal penalties, and will be prosecuted to
 *  the maximum extent under the law.
 *
 *  ---------------------------------------------------------------------------------------
 * Author:zhanghui
 * Date:2017/1/18
 * Desc:
 *
 * ======================================================================================== */

import cn.xiaojs.xma.R;

public class SourceConfig {
    public static int[] pors = new int[] {
            R.drawable.por_1,
            R.drawable.por_2,
            R.drawable.por_3,
            R.drawable.por_4,
            R.drawable.por_5,
            R.drawable.por_6,
            R.drawable.por_7,
            R.drawable.por_8,
            R.drawable.por_9,
            R.drawable.por_10,
            R.drawable.por_11,
            R.drawable.por_12,
            R.drawable.por_13,
            R.drawable.por_14,
            R.drawable.por_15,
            R.drawable.por_16,
            R.drawable.por_17,
            R.drawable.por_18,
            R.drawable.por_19,
            R.drawable.por_20,
            R.drawable.por_21,
            R.drawable.por_22,
            R.drawable.por_23,
            R.drawable.por_24,
            R.drawable.por_25,
            R.drawable.por_26,
            R.drawable.por_27,
            R.drawable.por_28,
            R.drawable.por_29,
            R.drawable.por_30,
            R.drawable.por_31,
            R.drawable.por_32,
            R.drawable.por_33,
            R.drawable.por_34,
            R.drawable.por_35,
            R.drawable.por_36,
            R.drawable.por_37,
            R.drawable.por_38,
            R.drawable.por_39,
            R.drawable.por_40,
            R.drawable.por_41,
            R.drawable.por_42,
            R.drawable.por_43,
            R.drawable.por_44,
            R.drawable.por_45,
            R.drawable.por_46,
            R.drawable.por_47,
            R.drawable.por_48,
            R.drawable.por_49,
            R.drawable.por_50,
            R.drawable.por_51,
            R.drawable.por_52,
            R.drawable.por_53,
            R.drawable.por_54,
            R.drawable.por_55,
            R.drawable.por_56,
            R.drawable.por_57,
            R.drawable.por_58,
            R.drawable.por_59,
            R.drawable.por_60,
            R.drawable.por_61,
            R.drawable.por_62,
            R.drawable.por_63,
            R.drawable.por_64,
            R.drawable.por_65,
            R.drawable.por_66,
            R.drawable.por_67,
            R.drawable.por_68,
            R.drawable.por_69,
            R.drawable.por_70,
            R.drawable.por_71,
            R.drawable.por_72,
            R.drawable.por_73,
            R.drawable.por_74
    };

    public static int[] lessons = new int[]{
        R.drawable.lesson_1,
        R.drawable.lesson_2,
        R.drawable.lesson_3,
        R.drawable.lesson_4,
        R.drawable.lesson_5,
        R.drawable.lesson_6,
        R.drawable.lesson_7,
        R.drawable.lesson_8,
        R.drawable.lesson_9,
        R.drawable.lesson_10,
        R.drawable.lesson_11,
        R.drawable.lesson_12,
        R.drawable.lesson_13,
        R.drawable.lesson_14,
        R.drawable.lesson_15,
        R.drawable.lesson_16,
        R.drawable.lesson_17,
        R.drawable.lesson_18,
        R.drawable.lesson_19,
        R.drawable.lesson_20,
        R.drawable.lesson_21,
        R.drawable.lesson_22,
        R.drawable.lesson_23,
        R.drawable.lesson_24,
        R.drawable.lesson_25,
        R.drawable.lesson_26,
        R.drawable.lesson_27,
        R.drawable.lesson_28,
        R.drawable.lesson_29,
        R.drawable.lesson_30,
        R.drawable.lesson_31,
        R.drawable.lesson_32,
        R.drawable.lesson_33,
        R.drawable.lesson_34,
        R.drawable.lesson_35,
        R.drawable.lesson_36,
        R.drawable.lesson_37,
        R.drawable.lesson_38,
        R.drawable.lesson_39,
        R.drawable.lesson_40,
        R.drawable.lesson_41,
        R.drawable.lesson_42,
        R.drawable.lesson_43,
        R.drawable.lesson_44,
        R.drawable.lesson_45,
        R.drawable.lesson_46,
        R.drawable.lesson_47,
        R.drawable.lesson_48,
        R.drawable.lesson_49,
        R.drawable.lesson_50,
        R.drawable.lesson_51,
        R.drawable.lesson_52,
        R.drawable.lesson_53,
        R.drawable.lesson_54,
        R.drawable.lesson_55,
        R.drawable.lesson_56,
        R.drawable.lesson_57,
        R.drawable.lesson_58
    };
}
